all:count sortwords family classifyNum
count:count.cpp
	g++ count.cpp -o count
sortwords:sortwords.cpp
	g++ sortwords.cpp -o sortwords
family:family.cpp
	g++ family.cpp -o family
classifyNum:classifyNum.cpp
	g++ classifyNum.cpp -o classifyNum
clean:
	rm count sortwords family classifyNum
delete:
	rm *.txt 
